### ISSUE TITLE
how recive channel message

### ISSUE THREAD

**Issue by amin1softco** [rubenlagus/Deepthought#1]
i want know how receive channel message with this project can you provide me simple example ?

**Comment by rubenlagus** [comment]
Hi @amin1softco, 

yes it is possible, just take my echo example and in the [UpdateHandler](https://github.com/rubenlagus/Deepthought/blob/master/src/main/java/org/telegram/plugins/echo/handlers/CustomUpdatesHandler.java), instead of overriding `onTLUpdateShortMessageCustom` and `onTLUpdateNewMessageCustom`, you need to override `onTLUpdateChannelNewMessageCustom`. With that, you should receive all the channel messages.

**Comment by amin1softco** [comment]
hi i write this one but not worked for me :
`@Override
    public void onTLUpdateChannelNewMessageCustom(TLUpdateChannelNewMessage update){
            BotLogger.info(LOGTAG, botConfig.languageCode + ": Received message from: "+update.getMessage() + update.getChannelId());

    }`

Apr 19, 2016 12:44:56 AM org.telegram.bot.services.BotLogger warning
WARNING: [UPDATESHANDLERBASE] Discarded update.TLUpdateChannelNewMessage#62ba04d9 with newPts: 1(0) and pts: 15

**Comment by amin1softco** [comment]
can provide for me straight forward example get all msg from channel - group - bot all msg send to my bot number ?

**Comment by amin1softco** [comment]
tnx solved
````java
      private void onTLUpdateChannelNewMessage(TLUpdateChannelNewMessage update) {
	
        TLAbsMessage message = update.getMessage();
        
	if ( message instanceof TLMessage) {
            BotLogger.debug(LOGTAG, "Received TLMessage");
            System.out.print("Received message from channel-----:"+((TLMessage) message).getMessage());
        } else {
            BotLogger.debug(LOGTAG, "Unsupported TLAbsMessage -> " + message.toString());
        }
````

but in super group and channel i think must use

**Comment by pmouraguedes** [comment]
Hi,is it still working? 

I'm having an issue described here:
https://github.com/rubenlagus/Deepthought/issues/35
